### ISSUE TITLE
Library not working on RN 0.61

### ISSUE THREAD

**Issue by EdLahatra** [Accengage/accengage-mobile-react-native-demo#11]
J'ai mis mon projet à niveau vers la norme RN O.61 et le message d'erreur suivant du module react-native-acc:

In file included from /project_path/node_modules/react-native-acc/ios/RNAcc/RNAccStates.h:11:
../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
